name: Keep Render Services Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  keepalive-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Health
        run: |
          curl -f https://ineco-backend.onrender.com/health || exit 0

  keepalive-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Frontend
        run: |
          curl -f https://ineco-frontend.onrender.com || exit 0
